---
title: "Conditionals and Loops"
author: "Alex Vand"
date: "8/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Conditional statements

#### Task 1

```{r}
pm2_5 <- 118

# Write an if - else if - else statement that returns “Low to moderate risk” if pm2_5 (for Particulate Matter 2.5) is less than 100, “Unhealthy for sensitive groups” if PM 2.5 is 100 <= pm2_5 < 150, and “Health risk present” if PM 2.5 is >= 150.

if(pm2_5 < 100) {
   print("Low to moderate risk")
} else if(pm2_5 >= 100 & pm2_5 < 150) {
   print("Unhealthy for sensitive groups")
} else if(pm2_5 >= 150) {
   print("Health risk present")
}
```

#### Task 2

```{r}
# Store the string “blue whale” as an object called species. Write an if statement that returns “You found a whale!” if the string “whale” is detected in species (hint: %in%), otherwise return nothing. Test by changing the species string & re-running to see output.

species <- "orca whale"
if(str_detect(species, "whale")) {
  print("You found a whale!")
}
```

#### Task 3

```{r}
# Create a vector stored as max_airtemp_c with a value of 24.1. Write an if else statement that will print “Temperature too high” if max_airtemp_c is greater than 27, or “Temperature OK” if temperature is less than or equal to 27.

max_airtemp_c <- c(27.03)

if(max_airtemp_c > 27) {
  print("Temperature too hight")
} else if(max_airtemp_c <= 27) {
  print("Temperature OK")
}
```

#### Task 4

```{r}
# Store the base price of a burrito as base_burrito with a value of 6.50. Store main_ingredent with a starting string of “veggie.” Write a statement that will return the price of a burrito based on what a user specifies as “main_ingredient” (either “veggie”, “chicken” or “steak”) given the following:
# A veggie burrito is the cost of a base burrito
# A chicken burrito costs 3.00 more than a base burrito
# A steak burrito costs 3.25 more than a base burrito

base_burrito <- 6.50
main_ingredient <- "steak"

switch(main_ingredient,
       "veggie" = print(base_burrito),
       "chicken" = print(base_burrito + 3.00),
       "steak" = print(base_burrito + 3.25))
```


## For loops

#### Task 5
```{r}
# Create a new vector called fish that contains the values 8, 10, 12, 23 representing counts of different fish types in a fish tank (goldfish, tetras, guppies, and mollies, respectively). Write a for loop that iterates through fish, and returns what proportion of total fish in the tank are that species. Assume that these counts represent all fish in the tank.

fish <- c("goldfish" = 8, "tetras" = 10, "guppies" = 12, "mollies" = 23)
for(i in seq_along(fish)) {
  print(fish[i] / sum(fish))
}
```

#### Task 6

```{r}
# There is an existing vector in R called month.name that contains all month names (just try running month.name in the Console to check it out). Write a for loop that iterates over all months in month.name and prints “January is month 1,” “February is month 2”, etc.
#Hint: you can index values in the month.name vector just like you would any other vector (e.g., try running month.name[5]).

for(i in seq_along(month.name)) {
  print(paste(month.name[[i]], "is month", i))
}
```


